apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
spec:
  replicas: 2
  resources:
    requests:
      cpu: 150m
      memory: 192Mi
    limits:
      cpu: 400m
      memory: 384Mi
